### ISSUE TITLE
Aes128Gcm get error

### ISSUE THREAD

**Issue by arlicle** [RustCrypto/AEADs#136]
```
use aes_gcm::Aes128Gcm; // Or `Aes128Gcm` 
use aead::{Aead, NewAead, generic_array::GenericArray};  
let key = GenericArray::clone_from_slice(b"an example very very secret key."); 
let aead = Aes128Gcm::new(key);  
let nonce = GenericArray::from_slice(b"unique nonce"); // 96-bits; unique per message 
let ciphertext = aead.encrypt(nonce, b"plaintext message".as_ref()).expect("encryption failure!"); 
let plaintext = aead.decrypt(nonce, ciphertext.as_ref()).expect("decryption failure!"); 
assert_eq!(&plaintext, b"plaintext message");
```

get error

thread 'main' panicked at 'Slice must be the same length as the array', /Users/edison/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.12.3/src/lib.rs:549:9

**Comment by tarcieri** [comment]
The problem here is the key is too long:

```rust
let key = GenericArray::clone_from_slice(b"an example very very secret key."); 
```

It's 32-bytes, and you're trying to use AES-128-GCM, which needs a 16-byte key.

I think if you set the `RUST_BACKTRACE=1` environment variable you should be able to get the full stack trace which shows it's this line in the code.

Sorry about `generic-array`, it's a bit annoying, but needed to build abstractions over things like key sizes.

**Comment by arlicle** [comment]
@tarcieri Thank you very much :)
