### ISSUE TITLE
Eax release

### ISSUE THREAD

**Issue by Flakebi** [RustCrypto/AEADs#275]
Hi,
Could you make a new release or pre-release of the `eax` crate?
It would be nice to have a version that includes #231.
Thanks!

**Comment by tarcieri** [comment]
It's a little tricky because HEAD presently contains prereleases targeting `aead` v0.4 and a forthcoming `cipher` v0.3 release (see https://github.com/RustCrypto/traits/issues/392).

We are planning on cutting new releases across-the-board ASAP, hopefully in the next week or two.

If that's acceptable they'll be out soon, or if not I can cut a special point release with just this feature.

**Comment by Flakebi** [comment]
Thanks for the update! That’s fine with me, no need to hurry.

**Comment by tarcieri** [comment]
Released in #299

**Comment by Flakebi** [comment]
Thanks!
