### ISSUE TITLE
Rust AES GCM cannot decrypt encryption done using Python's Pycryptodome

### ISSUE THREAD

**Issue by nikhilavrio** [RustCrypto/AEADs#417]
Python Code

``` python
bdata = data.encode()
nonce = secrets.token_bytes(12)
cipher = AES.new(aes_key, AES.MODE_GCM, nonce=nonce)
ciphertext, tag = cipher.encrypt_and_digest(bdata)
json_k = [ 'nonce', 'ciphertext', 'tag' ]
json_v = [ base64.standard_b64encode(x).decode('utf-8') for x in [cipher.nonce, ciphertext, tag ]]
result = json.dumps(dict(zip(json_k, json_v)))
```

Reference - https://pycryptodome.readthedocs.io/en/latest/src/cipher/modern.html#gcm-mode

Rust Code
```rust
    let key = Key::from_slice(&password);
    let cipher = Aes256Gcm::new(key);
    let nonce = Nonce::from_slice(&nonce_in);
    let plaintext = cipher.decrypt(nonce, ciphertext.as_ref()); 

```
Rust code throws exception at plaintext line.

**Comment by tarcieri** [comment]
Please provide a complete, self-contained Rust reproduction of the issue including examples of `key`, `cipher`, `nonce`, `plaintext`, and `ciphertext`.

Especially since you have a lot of format encoding related stuff happening in your Python code, it seems likely you are mangling data somewhere along the way.
