### ISSUE TITLE
Usage example for aes-gcm with arbitrary-length password

### ISSUE THREAD

**Issue by pieterdd** [RustCrypto/AEADs#505]
As a novice to cryptography who's just trying to encrypt a file using good security practices, I feel a bit out of my depth here.

There's a [helpful usage snippet](https://docs.rs/aes-gcm/0.10.1/aes_gcm/index.html#usage) in the aes-gcm docs. But since my use case is a simple application that stores 2FA tokens in a config file protected by a password chosen by the end user, I assume I need to use a key derivation function.

Could you provide a code sample for this purpose, or perhaps even better, point me to an alternative for `Aes256Gcm::generate_key(&mut OsRng)` that can derive a key from an arbitrary-length password?

**Comment by tarcieri** [comment]
We don't currently have a good place to show "recipes" with combinations of various algorithms like this.

Perhaps eventually it can go in https://github.com/rustcrypto/book. Can you file an issue there?

Because there are so many different ways various cryptographic algorithms can be combined, documenting them all can be laborious, and there's a question of whether in this case password-based encryption should go in the encryption crate or the PBKDF crate, which is why something like the book is probably the best home for it.

**Comment by pieterdd** [comment]
Fair enough, aes-gcm is just one piece of the puzzle. Hopefully this is a good use case to kickstart the book.
