### ISSUE TITLE
What is the type of Nonce generated from Aes128Gcm?

### ISSUE THREAD

**Issue by itsfloki** [RustCrypto/AEADs#540]
What will be the type of this nonce? I want to store the nonce in a struct. 
```rs
    let nonce: Nonce<> = Aes128Gcm::generate_nonce(&mut OsRng); // 96-bits; unique per message
```

**Comment by newpavlov** [comment]
Have you read the [docs](https://docs.rs/aes-gcm/latest/aes_gcm/trait.AeadCore.html#method.generate_nonce)? You can clearly see that it returns `GenericArray<u8, N>`, where `N` is nonce size, which in this case is equal to [`U12`](https://docs.rs/aead/0.5.2/aead/consts/type.U12.html). So the final type is `GenericArray<u8, U12>`. You also could use the [`Nonce`](https://docs.rs/aes-gcm/latest/aes_gcm/type.Nonce.html) alias and write `Nonce<U12>`.

P.S.: Instead of issue trackers I recommend using either [URLO](users.rust-lang.org/), or [our Zulip](https://rustcrypto.zulipchat.com/#all_messages) for such questions.
